LedgerHQ/wallet-api

- spec/client/README.md
Add the base of the Client API specification.
The main points of attention in this spec are the serialization and deserialization that the client needs to take care of and the error handling for the `completeExchange` method.
The rest is just implementing the RPC spec defined in `/spec/rpc/README.md`
> 📝 [Support][LIVE-3591] create client spec

- spec/core/types.md
Add specification for types based on https://github.com/LedgerHQ/live-app-sdk/blob/main/docs/reference/modules.md
It's a good first step for now but should be refined after first iteration of client, api and common packages implementations to properly organize and define typed that are common to the client and api internal workings, or client or api specific (and exposed to the end-user).
---
Some thoughts on current types:
It looks like some types are not related to the specification (are more implementation specific), like `EcdsaSignature`, `ExchangeDeviceTxId` or `ExchangePayload`.
Also, some types are actually not used anywhere today (like `ApplicationDetails` or `DeviceInfo`).
Some types are also Ledger Live specific like `RawSignedTransaction`.
It feels like all these types should …
> Add types spec

- .github/workflows/release.yml
- package.json
- packages/client/package.json
- packages/eslint-config-custom/package.json
Instead of doing a pre-release (`next` something) on `main` and tag to do the release, we use the changesets action (https://github.com/changesets/action) to help us create and update a PR whenever there is new changesets on `main`
> chore: release CI [LIVE-3193]

- .vscode/notebooks/my-work.github-issues
- .vscode/notebooks/team-inbox.github-issues
Add github issues notebooks to easily track all PR and issues related to the team at large in a single place.
Furthermore, since notebooks are versioned, they can easily shared, updated and reviewed like any other textefile (configuration, doc, code) 🙌 
You will need the [GitHub issue notebooks extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-github-issue-notebooks) to get the full out of this. 
Some inspirations from the vscode team:
https://github.com/microsoft/vscode/tree/main/.vscode/notebooks
cf. https://code.visualstudio.com/blogs/2021/11/08/custom-notebooks#_github-issues-notebook
> Add github issues notebooks

- .changeset/late-tables-develop.md
- packages/client/src/WalletAPIClient.ts
- packages/client/src/modules/Bitcoin.ts
- packages/core/src/spec/rpcHandlers/WalletHandlers.ts
- packages/core/src/spec/types/BitcoinGetXPub.ts
- packages/core/src/spec/types/index.ts
- packages/server/src/internalHandlers/bitcoin.ts
- packages/server/src/internalHandlers/index.ts
- packages/server/src/types.ts
- packages/simulator/src/profiles/standard/index.ts
- packages/simulator/tests/simulator.spec.ts
fixes #68 
Add a `getXPub` method in a new `bitcoin` module to allow clients to request specific bitcoin account xpub.
Add tests in the simulator to test this behaviour.
> Add getXPub bitcoin module method

- .changeset/fifty-swans-cry.md
- packages/core/src/spec/types/AccountList.ts
- packages/core/src/spec/types/CurrencyList.ts
- packages/server/src/internalHandlers/account.ts
- packages/server/src/internalHandlers/currency.ts
Fix type of `currency.list` and `account.list` server handlers to match method signatures on client side ([this](https://github.com/LedgerHQ/wallet-api/blob/main/packages/client/src/WalletAPIClient.ts#L224-L239) and [this](https://github.com/LedgerHQ/wallet-api/blob/main/packages/client/src/WalletAPIClient.ts#L157-L170) respectively).
For example, this is valid from the client side:
`walletAPIClientInstance.listCurrencies()`
But is not from the server side (handler), which would request this instead:
`walletAPIClientInstance.listCurrencies({})`
📝  Notes:
- Consistency of methods signature schema / types should be enforced between client and server
> fix type on server handlers to match signature on client side

- apps/wallet-api-tools/.eslintrc.js
- apps/wallet-api-tools/.eslintrc.json
- apps/wallet-api-tools/package.json
- apps/wallet-api-tools/src/Editor.tsx
- apps/wallet-api-tools/src/Input.tsx
- apps/wallet-api-tools/src/TemplateSelector/index.tsx
- packages/eslint-config-custom/next.js
- packages/eslint-config-custom/package.json
- pnpm-lock.yaml
Uses typescript & prettier with next for eslint
Also fixed lint issues and always use 2 spaces for `JSON.stringify`
> chore: better eslint next config

- .changeset/strong-ducks-learn.md
- packages/client/package.json
- pnpm-lock.yaml
Moved from peerDependencies as the client will not work without it
We can also export the transport from this package like before in another PR if needed
> chore: move `@ledgerhq/hw-transport` to deps

- .changeset/rare-roses-cross.md
- packages/client-react/prod-esm.tsconfig.json
- packages/client-react/prod.tsconfig.json
- packages/client/prod-esm.tsconfig.json
- packages/client/prod.tsconfig.json
- packages/core/prod-esm.tsconfig.json
- packages/core/prod.tsconfig.json
- packages/manifest-validator/prod-esm.tsconfig.json
- packages/manifest-validator/prod.tsconfig.json
- packages/server/prod-esm.tsconfig.json
- packages/server/prod.tsconfig.json
- packages/simulator/prod-esm.tsconfig.json
- packages/simulator/prod.tsconfig.json
Fixes #204
The issue was introduced when doing the refactor to improve the IDE experience https://github.com/LedgerHQ/wallet-api/pull/170
As we are re-exporting some libraries such as core in the client lib, with the root tsconfig and the baseUrl set to the root of the monorepo, the build folder would actually contain all re-exported code.
> fix: missing baseUrl for prod tsconfig

- .changeset/wet-bats-thank.md
- packages/server/src/WalletAPIServer.ts
- packages/server/src/react.ts
We switch to using a useRef instead of the useMemo to avoid recreating the server instance whenever the config changes.
Instead we added a `setConfig` to the server class to be able to update it on an existing instance.
This should help for some cases where the server would return an empty value on some endpoints.
> feat(server): react hooks use ref instead of memo [LIVE-8773]

- .changeset/many-rules-rhyme.md
- packages/core/src/families/cosmos/serializer.ts
- packages/core/src/families/cosmos/types.ts
- packages/core/src/families/cosmos/validation.ts
- packages/core/tests/serializers.spec.ts
Adds optional `validators` and `sourceValidator` properties to the `CosmosTransaction` interface and adjustment to the related serializer, and schema validation based on a Ledger Live Common type found in the Ledger Live monorepo [here](https://github.com/LedgerHQ/ledger-live/blob/de06c81fd976a46fa8b637cef7d284602d46b16b/libs/ledger-live-common/src/families/cosmos/types.ts#L162C25-L162C25). 
We are currently building a ledger live app for [StakeKit](https://www.stakek.it/) that offers users a unified non-custodial staking experience across a wide range of networks and protocols. We were unable to use the Wallet API to sign and broadcast Cosmos Delegate transactions. After investigating the ledger-live monorepo and modifying the CosmosTransaction interface, serializer and schema validation …
> Add optional validator properties to CosmosTransaction

- apps/docs/pages/core/modules/exchange.mdx
- apps/wallet-api-tools/src/TemplateSelector/index.tsx
- packages/client/src/modules/Exchange.ts
- packages/core/src/spec/types/ExchangeComplete.ts
- packages/server/src/internalHandlers/exchange.ts
- packages/server/src/types.ts
- spec/rpc/README.md
Add params to save swap history
https://ledgerhq.atlassian.net/browse/LIVE-8943
> feat: add params to save swap history

- packages/simulator/src/transport.ts
- packages/simulator/tests/server.spec.ts
- packages/simulator/tests/simulator.spec.ts
Missing tests for
Issue with the tests of
> test(simulator): Added tests for all modules except device and exchange

- .changeset/rude-boxes-flash.md
- packages/core/src/JSONRPC/RpcNode.ts
- packages/core/src/JSONRPC/helpers.ts
- packages/core/src/JSONRPC/types.ts
- packages/core/src/JSONRPC/validation.ts
- packages/core/src/spec/types/StorageSet.ts
- packages/simulator/tests/simulator.spec.ts
[JIRA ISSUE: LIVE-9765](https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-9765)
bug fix video with logs, _trying out storage.set function call @ 00:26_ : 
https://github.com/LedgerHQ/wallet-api/assets/5050709/fa79a2f4-0180-4671-a61b-6115a9b22e77
One first way to solve the problem didn't end up working (@RamyEB , @Justkant), as the `params` object was as such: 
```js
{
...
result: undefined,
}
```
Thus overriding the empty object we would set above.
> defaults results to an empty object if null or undefined

- .changeset/tidy-berries-wave.md
- packages/core/src/transports/WindowMessageTransport.ts
In order to support browserViews in electron
> fix: WindowMessageTransport accepts same origin messages [LIVE-10439]

- .changeset/eight-foxes-accept.md
- .changeset/new-papayas-lick.md
- packages/client-react/src/components/WalletAPIProvider/index.tsx
- packages/client-react/src/components/WalletAPIProvider/types.ts
- packages/client-react/src/hooks/useWalletAPIClient.ts
- packages/client/src/WalletAPIClient.ts
- packages/client/src/modules/Wallet.ts
- packages/core/src/spec/types/CustomRequest.ts
- packages/simulator/tests/server.spec.ts
Still missing some examples of usage and docs on how to setup the type safety in a project
> feat: improve custom handler types [LIVE-9760]

- .changeset/metal-dolls-punch.md
- packages/core/src/families/polkadot/serializer.ts
- packages/core/src/families/polkadot/types.ts
- packages/core/src/families/polkadot/validation.ts
📝 Description
Adds optional attributes:
- `validators`
- `numOfSlashingSpans`
- `rewardDestination`
to the `PolkadotTransaction` interface and changes to the validation and serialization, based on a Ledger Live type found in the Ledger Live monorepo [here](https://github.com/LedgerHQ/ledger-live/blob/de06c81fd976a46fa8b637cef7d284602d46b16b/libs/coin-polkadot/src/types.ts#L65).
❓ Context
We are currently building a ledger live app for [StakeKit](https://www.stakek.it/) that offers users a unified non-custodial staking experience across a wide range of networks and protocols. 
Like we did for Cosmos [here](https://github.com/LedgerHQ/wallet-api/pull/220) a while back, we are now adding support to Polkadot validator staking and need this type to support and serialize all the fields needed …
> Add optional attributes to PolkadotTransaction

- .changeset/wet-donkeys-obey.md
- apps/wallet-api-tools/manifest.json
- packages/core/src/spec/types/AccountReceive.ts
- packages/core/src/spec/types/TransactionSign.ts
- packages/core/src/spec/types/TransactionSignAndBroadcast.ts
- packages/server/src/internalHandlers/account.ts
- packages/server/src/internalHandlers/transaction.ts
- packages/server/src/types.ts
Handle empty token accounts by using `tokenCurrency` - an (optional) parameter - for the `transaction.sign` and `transaction.signAndBroadcast` wallet api handlers. 
PR ledger live: https://github.com/LedgerHQ/ledger-live/pull/5925 
Jira issue: https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-10041
> feat: add `tokenCurrency` to support token accounts in some handlers

- .changeset/light-cycles-tickle.md
- packages/simulator/src/profiles/standard/index.ts
Fixes a small issue in the simulator standard profile that shouldn't affect real apps as it's only used for testing purposes
Reported by the code scanning feature of github here: https://github.com/LedgerHQ/wallet-api/security/code-scanning/1
> fix: use Map to avoid prototype-polluting assignment

- .changeset/lovely-boats-pay.md
- packages/simulator/package.json
- packages/simulator/src/profiles/device/index.ts
- pnpm-lock.yaml
Removed the need for us to have a dependency on `@ledgerhq/hw-transport-http` in order to remove the old axios dependency
Reported by github dependabot alerts: https://github.com/LedgerHQ/wallet-api/security/dependabot/3
> fix: remove `@ledgerhq/hw-transport-http` that uses an old axios version

- .changeset/fair-mangos-suffer.md
- apps/docs/pages/docs/discover/wallet-api/appendix/transaction.mdx
- packages/core/src/spec/types/TransactionSign.ts
- packages/core/src/spec/types/TransactionSignAndBroadcast.ts
Adding the optional dependencies option for transaction sign, to support installing more apps if needed on a transaction
> feat: add optional dependencies option on transaction sign and broadcast

- .changeset/three-numbers-pretend.md
- packages/client-react/src/components/WalletAPIProvider/index.tsx
- packages/client-react/src/components/WalletAPIProvider/types.ts
Allows to pass a user created client instead of creating it in the provider
> feat: add client prop to the react provider

- .changeset/nasty-rockets-lick.md
- apps/wallet-api-tools/src/CommandSelector/index.tsx
- packages/client/src/modules/Account.ts
- packages/core/src/spec/types/AccountRequest.ts
- packages/server/src/internalHandlers/account.ts
- packages/server/src/types.ts
- packages/simulator/tests/simulator.spec.ts
To make the modular asset drawer customizable we need to pass some configuration when account.request is triggered. 
It follows this structure : 
We are using a general string type for those parameters instead of string literals. This is done to avoid having a dependency on wallet API if we extend those parameters to support additional values as explained [here](https://ledgerhq.atlassian.net/wiki/spaces/WXP/pages/5745082390/Modularization+Parameter?focusedCommentId=5755174932).
Context : [LIVE-18776](https://ledgerhq.atlassian.net/browse/LIVE-18776)
[LIVE-18776]: https://ledgerhq.atlassian.net/browse/LIVE-18776?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add drawerConfiguration to account request

- .changeset/strong-pans-argue.md
- packages/client/src/modules/Transaction.ts
This pull request introduces a new capability to the Wallet API client, allowing users to sign raw transactions using the connected wallet. The main change is the addition of the `signRaw` method to the `TransactionModule`, which enables signing and optionally broadcasting raw transactions in a currency-specific format.
**New Feature: Raw Transaction Signing**
* Added a new `signRaw` method to the `TransactionModule` in `packages/client/src/modules/Transaction.ts`, allowing users to sign and optionally broadcast raw transactions. This method accepts an account ID, a raw transaction string, and optional parameters, returning the signed transaction hex and an optional transaction hash.
* Imported the necessary types and schemas (`schemaTransactionSignRaw`, `TransactionSignRaw`) from …
> feat(client): add signRaw method for signing raw transactions
