LedgerHQ/wallet-api

CONTRIBUTING.md, README.md, SECURITY.md
Add basic Readme and contributing guidelines for the monorepo.
Both the Readme and Contributing guidelines will need to be improved and enhanced once the project is properly setup and structured.
This PR includes a [mermaid](https://mermaid-js.github.io/mermaid/#/) chart.
Cf. this [Github blog post](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) to learn more about mermaid 🧜‍♀️ 
On VS Code, you can use [this](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) extension to visualize it in VS Code's builtin markdown preview
TODO:
=> Create repo readme

CONTRIBUTING.md
Add first iteration of contribution guidelines
[LIVE-3659](https://ledgerhq.atlassian.net/browse/LIVE-3659)
=> LIVE-3659: update contributing guidelines

spec/core/errors.md
Add list of possible error returned by the server.
Can be extended over time with new errors
=> Create errors spec

.vscode/notebooks/team-inbox.github-issues
Following team renaming on github
=> Update team reference

.changeset/kind-fireants-buy.md, packages/manifest-validator/src/schema/schema.json, packages/manifest-validator/tests/manifests/dapp/dapp-manifest.test.json, packages/manifest-validator/tests/manifests/dapp/invalid-dapp-manifest.test.json, packages/manifest-validator/tests/manifests/walletApp/invalid-walletApp-manifest.test.json, packages/manifest-validator/tests/manifests/walletApp/walletApp-manifest.test.json, packages/manifest-validator/tests/manifests/webBrowserApp/invalid-webBrowser-manifest.test.json, packages/manifest-validator/tests/manifests/webBrowserApp/webBrowser-manifest.test.json
=> change manifestVersion to version

.changeset/smooth-years-marry.md, packages/core/src/families/common.ts
Simple export of the `FAMILIES` as const to be used in code
=> feat(core): export FAMILIES const

README.md, SUPPORT.md
Add support ressources file, cf. https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-support-resources-to-your-project
https://ledgerhq.atlassian.net/browse/LIVE-3658
[LIVE-3658]: https://ledgerhq.atlassian.net/browse/LIVE-3658?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add support doc

website/docusaurus.config.js
Following setup of domaine for the website vercel project by infra team, updating the url in config file
=> Update doc website URL

packages/client/src/WalletAPIClient.ts, website/docs/reference/api/client/classes/WalletAPIClient.md, website/docs/reference/api/client/index.md
Update `requestAccount` function doc to better highlight how to find cryptocurrencies and token ids.
cf. https://ledgerhq.atlassian.net/browse/LIVE-705
=> [DOC 📚][LIVE-705] update `requestAccount` function doc

package.json, pnpm-lock.yaml, turbo.json, website/package.json
Added the client and server as dev dependencies so that turborepo can build the correct dependency tree
=> chore: fix website turborepo setup

.changeset/flat-turkeys-relate.md, packages/eslint-config-custom/index.js, packages/eslint-config-custom/package.json, packages/server/package.json, packages/server/src/index.ts, packages/server/src/react.ts, pnpm-lock.yaml, website/docs/reference/api/server/index.md
=> Extract useWalletAPIServer hook from ledger live

.changeset/nine-needles-know.md, packages/client/src/WalletAPIClient.ts, packages/client/src/modules/Account.ts, packages/client/src/modules/Currency.ts, packages/client/src/modules/Device.ts, packages/client/src/modules/Message.ts, packages/client/src/modules/Transaction.ts, website/docs/reference/api/client/classes/WalletAPIClient.md, website/docs/reference/api/client/index.md, website/docs/reference/api/client/interfaces/TransactionCommon.md
=> refactor: client into modules

apps/wallet-api-tools/manifest.json, apps/wallet-api-tools/src/TemplateSelector/index.tsx
=> added more templates to wallet-api-tools

.changeset/metal-mails-visit.md, packages/core/src/errors/creators.ts, packages/core/src/errors/types.ts, packages/server/src/internalHandlers/storage.ts, website/docs/reference/api/client/classes/ServerError.md, website/docs/reference/api/client/index.md
Storage api  store access is currently "open bar" which can be an issue.
This PR enforce for now that live apps can only read and write data from their own store. A future update will allow us to list exposed stores in the manifest.
=> Added a simple store permission system and matching error

.changeset/early-walls-glow.md, packages/core/tests/serializers.spec.ts
=> Add missing (de)serializer tests for Near and Neo family

apps/docs/pages/react/migration-guide.mdx
This PR adds a proposal for a migration guide from platform-api to wallet-api
=> first draft for migration guide

.changeset/happy-rivers-agree.md, apps/wallet-api-tools/package.json, apps/wallet-api-tools/src/Editor.tsx, apps/wallet-api-tools/src/Input.tsx, pnpm-lock.yaml
Now using `@uiw/codemirror-extensions-langs` to load compatible langs (https://uiwjs.github.io/react-codemirror/#/extensions/languages)
More infos on the issue we fix here: https://github.com/uiwjs/react-codemirror/issues/480
=> fix(wallet-api-tools): `@codemirror/state` deps version mismatch

apps/docs/pages/react/hooks/_meta.json, apps/docs/pages/react/hooks/useAccounts.mdx, apps/docs/pages/react/hooks/useCurrencies.mdx, packages/client-react/src/hooks/useAccounts.ts, packages/client-react/src/hooks/useCurrencies.ts
#152 
- Add `useAccounts` page
- Fix hooks return type names
- Adjust header size across pages
=> docs(hooks): Add docs for `useAccounts` hook

.changeset/rude-students-battle.md, apps/wallet-api-tools/src/TemplateSelector/index.tsx, packages/core/src/spec/types/ExchangeComplete.ts
=> feat: add swap support custom fee

.changeset/lemon-books-wink.md, packages/server/src/react.ts
Also updates the initialisation of the server
=> fix: react hook return value

apps/docs/pages/appendix/manifest.mdx
=> Add documentation for dynamic generation

.changeset/little-peaches-explode.md, apps/docs/pages/core/modules/exchange.mdx, packages/client/src/modules/Exchange.ts, packages/core/src/spec/types/ExchangeComplete.ts, packages/server/src/internalHandlers/exchange.ts, packages/server/src/types.ts, spec/rpc/README.md
Add an optional `tokenCurrency` field for the swap and fund
JIRA: https://ledgerhq.atlassian.net/browse/LIVE-10291
=> feat(exchange): add optional tokenCurrency [LIVE-10291]

apps/docs/pages/appendix/manifest.mdx, packages/manifest-validator/src/schema/schema.json
complete description in main PR in LL: https://github.com/LedgerHQ/ledger-live/pull/5574  
JIRA issue: https://ledgerhq.atlassian.net/browse/LIVE-10130
=> feat(recover): new cta, subtitle and highlight fields in manifest

.changeset/brave-icons-repair.md, packages/core/src/accounts/serializers.ts, packages/core/src/accounts/types.ts, packages/core/src/accounts/validation.ts, packages/server/src/internalHandlers/account.ts
JIRA issue: https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-11197
Ledger Live pull request : https://github.com/LedgerHQ/ledger-live/pull/6157
=> handle parent account id being returned when requesting account

README.md, packages/client-react/README.md, packages/client/README.md, packages/manifest-validator-cli/README.md, packages/manifest-validator/README.md, packages/simulator/README.md
JIRA: https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-11507
=> chore: update discord link [LIVE-11507]

.changeset/polite-melons-look.md, packages/core/package.json, packages/core/src/families/common.ts, packages/core/src/families/index.ts, packages/core/src/families/serializer.ts, packages/core/src/families/types.ts, packages/core/src/families/validation.ts, packages/core/src/families/vechain/serializer.ts, packages/core/src/families/vechain/types.ts, packages/core/src/families/vechain/validation.ts, packages/core/tests/serializers.spec.ts, pnpm-lock.yaml
Add vechain family, I need to add a test case for the family serialisation
=> feat: add vechain family [LIVE-9715]

.changeset/big-waves-press.md, packages/core/package.json, packages/core/src/families/common.ts, packages/core/src/families/index.ts, packages/core/src/families/serializer.ts, packages/core/src/families/stacks/serializer.ts, packages/core/src/families/stacks/types.ts, packages/core/src/families/stacks/validation.ts, packages/core/src/families/types.ts, packages/core/src/families/validation.ts, pnpm-lock.yaml
Add stacks family, ~~I need to add a test case for the family serialisation~~ (or maybe I should)
=> feat: add stacks family

.changeset/violet-dingos-smash.md, packages/core/src/families/common.ts, packages/core/src/families/index.ts, packages/core/src/families/internet_computer/serializer.ts, packages/core/src/families/internet_computer/types.ts, packages/core/src/families/internet_computer/validation.ts, packages/core/src/families/serializer.ts, packages/core/src/families/types.ts, packages/core/src/families/validation.ts
Add internet_computer (ICP) family
JIRA: [LIVE-12221]
[LIVE-12221]: https://ledgerhq.atlassian.net/browse/LIVE-12221?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [LIVE-1222] 1feat: adds internet computer family

.changeset/shaggy-boxes-flow.md, packages/core/src/families/casper/serializer.ts, packages/core/src/families/casper/types.ts, packages/core/src/families/casper/validation.ts, packages/core/src/families/common.ts, packages/core/src/families/index.ts, packages/core/src/families/serializer.ts, packages/core/src/families/types.ts, packages/core/src/families/validation.ts
Add internet_computer (ICP) family
JIRA: [LIVE-12224]
[LIVE-12224]: https://ledgerhq.atlassian.net/jira/software/c/projects/LIVE/boards/623?selectedIssue=LIVE-12224
=> [LIVE-1224] feat: adds casper family 

packages/simulator/tests/simulator.spec.ts
Add some checks for https://github.com/LedgerHQ/wallet-api/pull/346
=> test: unknown currency should work

.changeset/short-kings-tell.md, packages/core/src/JSONRPC/RpcNode.ts, packages/core/src/errors/creators.ts, packages/core/src/errors/types.ts, packages/simulator/package.json, packages/simulator/tests/simulator.spec.ts, pnpm-lock.yaml
Fixes serializeError handling and allow passthrough for unknown errors
Add tests for error handling
=> fix: serializeError handling and allow passthrough for unknown errors [LIVE-12524]

apps/docs/pages/APIs/wallet-api/core/modules/account.mdx, apps/docs/pages/APIs/wallet-api/core/modules/bitcoin.mdx, apps/docs/pages/APIs/wallet-api/core/modules/currency.mdx, apps/docs/pages/APIs/wallet-api/core/modules/device.mdx, apps/docs/pages/APIs/wallet-api/core/modules/exchange.mdx, apps/docs/pages/APIs/wallet-api/core/modules/message.mdx, apps/docs/pages/APIs/wallet-api/core/modules/storage.mdx, apps/docs/pages/APIs/wallet-api/core/modules/transaction.mdx, apps/docs/pages/APIs/wallet-api/core/modules/wallet.mdx, apps/docs/pages/APIs/wallet-api/react/hooks/useAccounts.mdx, apps/docs/pages/APIs/wallet-api/react/hooks/useCapabilities.mdx, apps/docs/pages/APIs/wallet-api/react/hooks/useCurrencies.mdx, apps/docs/pages/APIs/wallet-api/react/hooks/useRequestAccount.mdx, apps/docs/pages/APIs/wallet-api/react/hooks/useSignAndBroadcastTransaction.mdx, apps/docs/pages/APIs/wallet-api/react/hooks/useSignMessage.mdx, apps/docs/pages/APIs/wallet-api/react/hooks/useSignTransaction.mdx, apps/docs/pages/APIs/wallet-api/react/hooks/useUserId.mdx, apps/docs/pages/APIs/wallet-api/react/hooks/useWalletInfo.mdx
https://ledgerhq.atlassian.net/browse/LIVE-11994
=> doc: add perms

apps/docs/pages/docs/discover.mdx, apps/docs/pages/docs/discover/dapp-browser.mdx, apps/docs/pages/docs/discover/dapp-browser/_meta.json, apps/docs/pages/docs/discover/dapp-browser/dapp-customisation.mdx, apps/docs/pages/docs/discover/dapp-browser/manifest.mdx, apps/docs/pages/docs/discover/dapp-browser/migration.mdx, apps/docs/pages/docs/discover/dapp-browser/plugin.mdx
https://ledgerhq.atlassian.net/browse/LIVE-11663
https://ledgerhq.atlassian.net/browse/LIVE-11984
https://ledgerhq.atlassian.net/browse/LIVE-11985
https://ledgerhq.atlassian.net/browse/LIVE-12008
=> docs: dapp browser v3 update [LIVE-11663]

README.md
JIRA: https://ledgerhq.atlassian.net/browse/LIVE-11926
=> remove coins not supported anymore

.changeset/hot-pianos-juggle.md, README.md, packages/core/src/families/aptos/serializer.ts, packages/core/src/families/aptos/types.ts, packages/core/src/families/aptos/validation.ts, packages/core/src/families/common.ts, packages/core/src/families/serializer.ts, packages/core/src/families/types.ts, packages/core/src/families/validation.ts, spec/core/types.md
Add support for Aptos Blockchain
LIVE-15798
=> feat: add support coin aptos

.changeset/olive-parrots-clap.md, packages/core/src/families/index.ts, packages/core/tests/serializers.spec.ts
Jira ticket: https://ledgerhq.atlassian.net/browse/LIVE-15801
=> test: serialization methods for Aptos

.changeset/brave-waves-yawn.md, packages/client/src/WalletAPIClient.ts, packages/client/src/modules/Account.ts, packages/core/src/spec/types/AccountRequest.ts, packages/server/src/internalHandlers/account.ts, packages/server/src/types.ts
=> feat: new param to customize account request

.changeset/stupid-falcons-tell.md, packages/core/src/families/common.ts, packages/core/src/families/index.ts, packages/core/src/families/serializer.ts, packages/core/src/families/sui/serializer.ts, packages/core/src/families/sui/types.ts, packages/core/src/families/sui/validation.ts, packages/core/src/families/types.ts, packages/core/src/families/validation.ts, packages/core/tests/serializers.spec.ts
=> feat: add sui family integration

.changeset/thin-jeans-trade.md, packages/core/package.json, packages/core/src/families/ton/serializer.ts, packages/core/src/families/ton/types.ts, packages/core/src/families/ton/validation.ts, packages/core/src/families/vechain/types.ts, pnpm-lock.yaml
Related to https://github.com/LedgerHQ/ledger-live/pull/9837
Also doing ticket [LIVE-13067]
[LIVE-13067]: https://ledgerhq.atlassian.net/browse/LIVE-13067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(ton): expose ton payload for all possible actions [LIVE-17777]

.changeset/stale-boxes-approve.md, package.json, packages/core/src/families/ton/serializer.ts, packages/core/tests/ton-serializers.spec.ts, patches/@ton__core.patch, pnpm-lock.yaml
Fix ton serializer and missing exhaustive check
Also adds some tests and patch `@ton/core` to make it work with jest
=> fix: ton payload serializer and missing exhaustive check

.changeset/afraid-mice-own.md, packages/client/src/modules/Account.ts, packages/core/src/spec/types/AccountRequest.ts, packages/server/src/internalHandlers/account.ts, packages/server/src/types.ts, packages/simulator/tests/simulator.spec.ts
Added a new account.request parameter named `useCase`
Added a new account.request wallet handler parameter named `areCurrenciesFiltered`
=> Account Request - useCase and areCurrenciesFiltered

.changeset/many-gorillas-enjoy.md, apps/wallet-api-tools/manifest.json, apps/wallet-api-tools/src/CommandSelector/index.tsx, packages/core/src/spec/methods.ts, packages/core/src/spec/rpcHandlers/WalletHandlers.ts, packages/core/src/spec/types/TransactionSignRaw.ts, packages/core/src/spec/types/index.ts, packages/server/src/internalHandlers/index.ts, packages/server/src/internalHandlers/transaction.ts, packages/server/src/types.ts
This pull request introduces a new method, `transaction.signRaw`, to the wallet API, enabling raw transaction signing. The update includes changes to the schema, handler interfaces, and internal server logic to support this new capability.
**Raw Transaction Signing Feature:**
* Added the `transaction.signRaw` method to the API manifest, schema definitions (`methods.ts`), and handler types, allowing clients to request raw transaction signing. [[1]](diffhunk://#diff-5a2472efd68576c2e0b85b7e380916b945efb2abadc0f16181f3ecc1ee751d36R1-R6) [[2]](diffhunk://#diff-0263b954b333c4717275edc87f415bd10c426dfac854e4759b4599544260edc2R31) [[3]](diffhunk://#diff-ace524472594c6dc09e375944530f91d9a2b0763e11bc102215952e8ae1a4d39R15) [[4]](diffhunk://#diff-d2519a906aa6e6147e9cd329cbd451c3555e48e7aa620172ad595 …
=> feat: add transaction.signRaw method and related schema for raw transaction signing [LIVE-20606]

.changeset/three-seahorses-act.md, README.md, packages/core/src/families/common.ts, packages/core/src/families/index.ts, packages/core/src/families/kaspa/serializer.ts, packages/core/src/families/kaspa/types.ts, packages/core/src/families/kaspa/validation.ts, packages/core/src/families/serializer.ts, packages/core/src/families/types.ts, packages/core/src/families/validation.ts, packages/core/tests/serializers.spec.ts, spec/core/types.md
https://ledgerhq.atlassian.net/browse/LIVE-21753
=> feat: Add Kaspa support
